kind: Workflow
metadata:
  generateName: builder-
spec:
  entrypoint: schedule-framework-builds
  arguments:
    parameters:
    - name: buildmap
      value: |
        [
        {
            "toolchain": "x86-64-core-i7--glibc--stable-2018.11-1",
            "framework": "openssl",
            "commit": "fed8dbea27b7e01ee934951b25c6ffd40ad1d5c3",
            "optlvl": "-O3"
        }
        ]
    - name: algomap
      value: |
        [
        {
            "algo": "aria-cbc",
            "keylen": "128"
        },
        {
            "algo": "aes-cbc",
            "keylen": "128"
        }
        ]
  templates:
  - name: schedule-framework-builds
    inputs:
      parameters:
      - name: buildmap
      - name: algomap
    steps:
    - - name: Schedule-Build
        template: schedule-build
        arguments:
          parameters:
          - name: toolchain
            value: "{{item.toolchain}}"
          - name: framework
            value: "{{item.framework}}"
          - name: commit
            value: "{{item.commit}}"
          - name: optlvl
            value: "{{item.optlvl}}"
          - name: algomap
            value: "{{inputs.parameters.algomap}}"
        withParam: "{{inputs.parameters.buildmap}}"

  - name: schedule-build
    inputs:
      parameters:
      - name: toolchain
      - name: framework
      - name: commit
      - name: optlvl
      - name: algomap
    steps:
    - - name: schedule
        template: build
        arguments:
          parameters:
          - name: toolchain
            value: "{{inputs.parameters.toolchain}}"
          - name: framework
            value: "{{inputs.parameters.framework}}"
          - name: commit
            value: "{{inputs.parameters.commit}}"
          - name: optlvl
            value: "{{inputs.parameters.optlvl}}"
          - name: algorithm
            value: "{{item.algo}}"
          - name: keylen
            value: "{{item.keylen}}"
        withParam: "{{inputs.parameters.algomap}}"
    - - name: reduce
        template: reduce
        arguments:
          parameters:
          - name: leaks
            value: "{{steps.schedule.outputs.parameters.leaks}}"


  - name: build
    inputs:
      parameters:
      - name: toolchain
      - name: framework
      - name: commit
      - name: optlvl
      - name: algorithm
      - name: keylen
    container:
      image: builder
      imagePullPolicy: "Never"
      command:
          - bash
          - '-c'
      args:
          - >-
            python3 builder.py {{inputs.parameters.toolchain}} {{inputs.parameters.framework}} {{inputs.parameters.commit}} {{inputs.parameters.optlvl}} {{inputs.parameters.algorithm}} {{inputs.parameters.keylen}}
    outputs:
      artifacts:
      - name: toolchain
        path: /build/results.zip
      parameters:
      - name: leaks
        valueFrom:
          path: /tmp/summary.json

  - name: reduce
    inputs:
      parameters:
      - name: leaks
    container:
      image: alpine
      command:
          - bash
          - '-c'
      args:
          - >-
            cat {{inputs.parameters.leaks}}

      